/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tech_thrive_catalyst.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GreetingEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5171350922070516911L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GreetingEvent\",\"namespace\":\"com.tech_thrive_catalyst.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"emoji\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"🙂\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GreetingEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GreetingEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GreetingEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GreetingEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GreetingEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GreetingEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GreetingEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GreetingEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GreetingEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String name;
  private java.lang.String message;
  private java.lang.String emoji;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GreetingEvent() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param message The new value for message
   * @param emoji The new value for emoji
   */
  public GreetingEvent(java.lang.String name, java.lang.String message, java.lang.String emoji) {
    this.name = name;
    this.message = message;
    this.emoji = emoji;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return message;
    case 2: return emoji;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = value$ != null ? value$.toString() : null; break;
    case 1: message = value$ != null ? value$.toString() : null; break;
    case 2: emoji = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.String getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'emoji' field.
   * @return The value of the 'emoji' field.
   */
  public java.lang.String getEmoji() {
    return emoji;
  }


  /**
   * Sets the value of the 'emoji' field.
   * @param value the value to set.
   */
  public void setEmoji(java.lang.String value) {
    this.emoji = value;
  }

  /**
   * Creates a new GreetingEvent RecordBuilder.
   * @return A new GreetingEvent RecordBuilder
   */
  public static com.tech_thrive_catalyst.avro.GreetingEvent.Builder newBuilder() {
    return new com.tech_thrive_catalyst.avro.GreetingEvent.Builder();
  }

  /**
   * Creates a new GreetingEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GreetingEvent RecordBuilder
   */
  public static com.tech_thrive_catalyst.avro.GreetingEvent.Builder newBuilder(com.tech_thrive_catalyst.avro.GreetingEvent.Builder other) {
    if (other == null) {
      return new com.tech_thrive_catalyst.avro.GreetingEvent.Builder();
    } else {
      return new com.tech_thrive_catalyst.avro.GreetingEvent.Builder(other);
    }
  }

  /**
   * Creates a new GreetingEvent RecordBuilder by copying an existing GreetingEvent instance.
   * @param other The existing instance to copy.
   * @return A new GreetingEvent RecordBuilder
   */
  public static com.tech_thrive_catalyst.avro.GreetingEvent.Builder newBuilder(com.tech_thrive_catalyst.avro.GreetingEvent other) {
    if (other == null) {
      return new com.tech_thrive_catalyst.avro.GreetingEvent.Builder();
    } else {
      return new com.tech_thrive_catalyst.avro.GreetingEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for GreetingEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GreetingEvent>
    implements org.apache.avro.data.RecordBuilder<GreetingEvent> {

    private java.lang.String name;
    private java.lang.String message;
    private java.lang.String emoji;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tech_thrive_catalyst.avro.GreetingEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.emoji)) {
        this.emoji = data().deepCopy(fields()[2].schema(), other.emoji);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing GreetingEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tech_thrive_catalyst.avro.GreetingEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.emoji)) {
        this.emoji = data().deepCopy(fields()[2].schema(), other.emoji);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.tech_thrive_catalyst.avro.GreetingEvent.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.tech_thrive_catalyst.avro.GreetingEvent.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.tech_thrive_catalyst.avro.GreetingEvent.Builder setMessage(java.lang.String value) {
      validate(fields()[1], value);
      this.message = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.tech_thrive_catalyst.avro.GreetingEvent.Builder clearMessage() {
      message = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'emoji' field.
      * @return The value.
      */
    public java.lang.String getEmoji() {
      return emoji;
    }


    /**
      * Sets the value of the 'emoji' field.
      * @param value The value of 'emoji'.
      * @return This builder.
      */
    public com.tech_thrive_catalyst.avro.GreetingEvent.Builder setEmoji(java.lang.String value) {
      validate(fields()[2], value);
      this.emoji = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'emoji' field has been set.
      * @return True if the 'emoji' field has been set, false otherwise.
      */
    public boolean hasEmoji() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'emoji' field.
      * @return This builder.
      */
    public com.tech_thrive_catalyst.avro.GreetingEvent.Builder clearEmoji() {
      emoji = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GreetingEvent build() {
      try {
        GreetingEvent record = new GreetingEvent();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.message = fieldSetFlags()[1] ? this.message : (java.lang.String) defaultValue(fields()[1]);
        record.emoji = fieldSetFlags()[2] ? this.emoji : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GreetingEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<GreetingEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GreetingEvent>
    READER$ = (org.apache.avro.io.DatumReader<GreetingEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.message);

    out.writeString(this.emoji);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString();

      this.message = in.readString();

      this.emoji = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString();
          break;

        case 1:
          this.message = in.readString();
          break;

        case 2:
          this.emoji = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










